name: Docker

on: 
  pull_request:
  push:
  workflow_run:
    workflows: ["GradleUp"]
    # branches: [main]
    types: 
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run my docker image
        run: |
          docker build -t customimage .
          # docker run --rm -it -v $(pwd):/repos customimage
          # cd repos
          # ./gradlew
