name: CI
on:
  pull_request:
  push:
  workflow_run:
    workflows: ["Deploy", "GradleUp"]
    # branches: [main]
    types: 
      - completed
  schedule:
    - cron: '0 3 * * SUN'

jobs:
  build:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        jvm_version: [8, 11, 14]
    runs-on: ${{ matrix.os }}-latest
    env:
      OS: ${{ matrix.os }}
      TERM: dumb
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jvm_version }}
      - name: Gradle
        run: |
          ./gradlew --info
