name: Docker

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run my docker image
        run: |
          docker build -t customimage .
          docker run --rm -i -v $(pwd):/ customimage
